baseURL = ''
languageCode = 'en-us'
title = 'BelloTech Insights'
paginate = 5
theme= 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Bellotech"
description = "This is the website of Abubakar Bello Mustapha (ABM), Msc. and I create educational content on Software developer. Some of you may know me as the **BelloTech**."
keywords = [ "Blog", "Portfolio", "Software Developer" ]
author = "Mustapha"

DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "BelloTech Insights"
  icon = "images/dp.jpeg"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Welcome!👋"
  subtitle = "This is the website of **Abubakar Bello Mustapha (ABM)**, MSc. in Computer Science at Swansea university, united Kingdom (UK) and I create educational content on Software developer. Some of you may know me as the **BelloTech**."
  imageUrl = "images/dp.jpeg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Bello"

    [[params.profileMode.buttons]]
    name = "Blogs"
    url = "blogs"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "projects"

  [params.homeInfoParams]
  Title = "Welcome!👋"
  Content = "This is the website of **Abubakar Bello Mustapha (ABM)**, Msc. and I create educational content on Software developer. Some of you may know me as the **BelloTech**."

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/Bellotechie"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/23137228/bellotech"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/bello1470"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mustapha-abubakar-9a55a1125/"

  

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = false

  

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]


[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blogs"
url = "/blogs/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2


